name: Deployment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          registry-url: "https://npm.pkg.github.com"
          node-version: "14.15.1"
      - run: |
          npm install --ignore-scripts
      - name: NPM run lint
        run: npm run lint
      - name: Deployment
        run: echo "Deployment Finished"
