name: Tests

on:
  push:
    branches-ignore: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          registry-url: "https://npm.pkg.github.com"
          node-version: "14.15.1"
      - run: |
          cd src
          npm install --ignore-scripts
          npm run lint
      - name: Tests
        run: echo "All tests are passed"
